FROM confluentinc/cp-server-connect-operator:5.5.1.0-ubi8

ADD ./confluentinc-kafka-connect-datagen /usr/share/java/confluentinc-kafka-connect-datagen
ADD ./confluentinc-kafka-connect-sftp-2.0.0 /usr/share/java/confluentinc-kafka-connect-sftp-2.0.0
